### PR TITLE
Update changelog.txt

### PR DESCRIPTION
**Pull request by mlipok**

### CODE REVIEW

**Comment by Danp2** [comment]
V0.6.0.2b-1 is current development version in the next-release branch. My thoughts were to maintain the updates list in the existing "issue" and then push the all at once.

I guess we could do the same this in a PR that won't get merged until the update is ready for release.

**Comment by mlipok** [comment]
"PR" ? What this mean ?

**Comment by Danp2** [comment]
PR - what we are currently discussing (a pull request). :laughing:

**Comment by mlipok** [comment]
As you can see, I'm really GitHub novice.

**Comment by mlipok** [comment]
> I guess we could do the same this in a PR that won't get merged until the update is ready for release.

As I understand now we will update this PullRequest each time you commit new change to FF.au3 in the next-release branch.

If so then I think Ok.
The first option "using the existing "issue" will be not such easy as maintaining this PR.

**Pull request closed without merging**
